/**
* Simple API overview
* A sample api specification document
*
* The version of the OpenAPI document: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.payments.starr.dto


import com.squareup.moshi.Json
/**
 * 
 * @param username 
 * @param publishedDate 
 * @param id 
 */

data class SampleRequest (
    @Json(name = "username")
    val username: kotlin.String,
    @Json(name = "publishedDate")
    val publishedDate: kotlin.String,
    @Json(name = "id")
    val id: kotlin.Int
)

